/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package figuritas;

/**
 *
 * @author ruben
 */
public class IAgregar extends javax.swing.JInternalFrame {

    /**
     * Creates new form IAgregar
     */
    ControlFigura ctrlFig;

    public IAgregar(ControlFigura ctrl) {
        initComponents();
        ctrlFig = ctrl;
        emptyText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        eNombre = new javax.swing.JTextField();
        ex = new javax.swing.JTextField();
        ey = new javax.swing.JTextField();
        eradio = new javax.swing.JTextField();
        ealtura = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        NoOk = new javax.swing.JButton();
        estatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("Circulo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Punto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cilindro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ex.setEnabled(false);

        ey.setEnabled(false);
        ey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyActionPerformed(evt);
            }
        });

        eradio.setEnabled(false);

        ealtura.setEnabled(false);
        ealtura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ealturaActionPerformed(evt);
            }
        });

        ok.setText("ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        NoOk.setText("Atras");
        NoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoOkActionPerformed(evt);
            }
        });

        estatus.setText("status");

        jLabel1.setText("Nombre");

        jLabel2.setText("x");

        jLabel3.setText("y");

        jLabel4.setText("radio");

        jLabel5.setText("altura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ex, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ey, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eradio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ealtura, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(estatus)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NoOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ok)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(eNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(ex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addGap(18, 18, 18)
                        .addComponent(eradio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ealtura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(NoOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int idSel = 0;

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        allDisabled();
        ex.setEnabled(true);
        ey.setEnabled(true);
        estatus.setText("Punto Seleccionado");
        idSel = 1;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        allDisabled();
        ex.setEnabled(true);
        ey.setEnabled(true);
        eradio.setEnabled(true);
        estatus.setText("Circulo Seleccionado");
        idSel = 2;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eyActionPerformed

    private void ealturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ealturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ealturaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        allDisabled();
        ex.setEnabled(true);
        ey.setEnabled(true);
        eradio.setEnabled(true);
        ealtura.setEnabled(true);
        estatus.setText("Cilindro Seleccionado");
        idSel = 3;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        //esto sera horrioble papus
        String text = "";
        Figura temp = null;
        if(!fieldsAreCorrect()){
            estatus.setText("No letras solo numeros -_-");
            return;
        }
        switch (idSel) {
            case 3 -> {
                temp = new Cilindro(eNombre.getText(), Integer.parseInt(ex.getText()), Integer.parseInt(ey.getText()), Integer.parseInt(eradio.getText()), Integer.parseInt(ealtura.getText()));
                text = ("Cilindro agregado: " + eNombre.getText());
            }
            case 2 -> {
                temp = new Circulo(eNombre.getText(), Integer.parseInt(ex.getText()), Integer.parseInt(ey.getText()), Integer.parseInt(eradio.getText()));
                text = ("Circulo agregado: " + eNombre.getText());
            }
            case 1 -> {
                temp = new Punto(eNombre.getText(), Integer.parseInt(ex.getText()), Integer.parseInt(ey.getText()));
                text = ("Punto agregado: " + eNombre.getText());
            }
            default -> {
                estatus.setText("Ninguna figura seleccionada");
                emptyText();
                return;
            }
        }
        if (ctrlFig.agregarFigura(temp)) {
            estatus.setText(text);
        } else {
            estatus.setText("Figura ya existe -_-: " + eNombre.getText());
        }
        emptyText();
    }//GEN-LAST:event_okActionPerformed

    private void NoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_NoOkActionPerformed

    private boolean fieldsAreCorrect() {
        int a;
        try {
            a = Integer.parseInt(ex.getText());
            a = Integer.parseInt(ey.getText());
            a = Integer.parseInt(eradio.getText());
            a = Integer.parseInt(ealtura.getText());
        } catch (Exception e) {
            return false;
        }
        return true;
    }

    private void allDisabled() {
        ex.setEnabled(false);
        ey.setEnabled(false);
        eradio.setEnabled(false);
        ealtura.setEnabled(false);
    }

    private void emptyText() {
        ex.setText("0");
        ey.setText("0");
        eradio.setText("0");
        ealtura.setText("0");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NoOk;
    private javax.swing.JTextField eNombre;
    private javax.swing.JTextField ealtura;
    private javax.swing.JTextField eradio;
    private javax.swing.JTextField estatus;
    private javax.swing.JTextField ex;
    private javax.swing.JTextField ey;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
